language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

script:
  - ant -version
  - ant -f rainbow/build/library.xml init
  - ant -f rainbow/build/library.xml download-lib
  - ant -f rainbow/build.xml
