dist: focal
language: java

jdk:
  - openjdk11

branches:
  only:
    - next

script:
  - ant -f rainbow/build.xml deploy
before_deploy:
  - git config --local user.name jinghui70
  - git config --local user.email jinghui70@gmail.com
  - export TRAVIS_TAG=${v5.0.0-$(date +'%Y%m%d%H%M%S')}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: dist/*
  skip_cleanup: true
